name: GitHub Actions Demo
on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
      - uses: actions/checkout@v3
      - run: ls
  Deploy_to_test:
    needs: [Build]
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."
  Deploy_to_Load-test:
    needs: [Build]
    environment: Load-Test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing..."
          sleep 15
  Deploy_to_prod:
    needs: [Deploy_to_test, Deploy_to_Load-test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Step x deploying..."
          sleep 10
      - run: |
          echo "Step x deploying..."
          sleep 10
      - run: |
          echo "Step x deploying..."
          sleep 10
      - run: |
          echo "Step x deploying..."
          sleep 10
      - run: |
          echo "Step x deploying..."
          sleep 10
    
